[package]
name = "python-sandbox"
version = "0.1.0"
authors = ["Daniel Conley <himself@danii.dev>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
discord-bridge = {path = "../discord-bridge"}
rustpython-vm = {path = "/home/danii/Programming/Rust/RustPython/vm"}
