name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - Kile
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. Kile#0606
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what your issue was
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How can we reproduce this issue?
      description: Give us some steps to consistently reproduce this issue
      placeholder: What did you do?
      value: "I pressed the red button"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen after following the steps described above?
      description: What was the expected response?
      placeholder: What should have happened
      value: "I should have gotten cookies"
  - type: textarea
    id: reality
    attributes:
      label: What actually happened after doing these steps?
      description: What broke?
      placeholder: What was the result
      value: "I got vegetables :c"
